export const types = {
  ADD_ARTICLE_REQUEST : 'ADD_ARTICLE_REQUEST',
  ADD_ARTICLE_SUCCESS : 'ADD_ARTICLE_SUCCESS',
  ADD_ARTICLE_FAILURE : 'ADD_ARTICLE_FAILURE',

  GET_ARTICLES_REQUEST : 'GET_ARTICLES_REQUEST',
  GET_ARTICLES_SUCCESS : 'GET_ARTICLES_SUCCESS',
  GET_ARTICLES_FAILURE : 'GET_ARTICLES_FAILURE',

  GET_SELECTED_ARTICLE : 'GET_SELECTED_ARTICLE',
  UNSELECT_ARTCILE : 'UNSELECT_ARTCILE',

  EDIT_ARTICLE_REQUEST : 'EDIT_ARTICLE_REQUEST',
  EDIT_ARTICLE_SUCCESS : 'EDIT_ARTICLE_SUCCESS',
  EDIT_ARTICLE_FAILURE : 'EDIT_ARTICLE_FAILURE',

  DELETE_ARTICLE_REQUEST : 'DELETE_ARTICLE_REQUEST',
  DELETE_ARTICLE_SUCCESS : 'DELETE_ARTICLE_SUCCESS',
  DELETE_ARTICLE_FAILURE : 'DELETE_ARTICLE_FAILURE',

  ADD_GALLERY_POST_REQUEST : 'ADD_GALLERY_POST_REQUEST',
  ADD_GALLERY_POST_SUCCESS : 'ADD_GALLERY_POST_SUCCESS',
  ADD_GALLERY_POST_FAILURE : 'ADD_GALLERY_POST_FAILURE',

  GET_GALLERY_POSTS_REQUEST : 'GET_GALLERY_POSTS_REQUEST',
  GET_GALLERY_POSTS_SUCCESS : 'GET_GALLERY_POSTS_SUCCESS',
  GET_GALLERY_POSTS_FAILURE : 'GET_GALLERY_POSTS_FAILURE',

  GET_SELECTED_GALLERY_POST : 'GET_SELECTED_GALLERY_POST',
  UNSELECT_GALLERY_POST : 'UNSELECT_GALLERY_POST',

  EDIT_GALLERY_POST_REQUEST : 'EDIT_GALLERY_POST_REQUEST',
  EDIT_GALLERY_POST_SUCCESS : 'EDIT_GALLERY_POST_SUCCESS',
  EDIT_GALLERY_POST_FAILURE : 'EDIT_GALLERY_POST_FAILURE',

  DELETE_GALLERY_POST_REQUEST : 'DELETE_GALLERY_POST_REQUEST',
  DELETE_GALLERY_POST_SUCCESS : 'DELETE_GALLERY_POST_SUCCESS',
  DELETE_GALLERY_POST_FAILURE : 'DELETE_GALLERY_POST_FAILURE',

  LOGIN_REQUEST : 'LOGIN_REQUEST',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAILURE : 'LOGIN_FAILURE',

  LOGOUT_REQUEST : 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE : 'LOGOUT_FAILURE',

  GET_SELECTED_ARTICLE_BY_URL : 'GET_SELECTED_ARTICLE_BY_URL',

  ADD_PARTNER_REQUEST : 'ADD_PARTNER_REQUEST',
  ADD_PARTNER_SUCCESS : 'ADD_PARTNER_SUCCESS',
  ADD_PARTNER_FAILURE : 'ADD_PARTNER_FAILURE',
  
  GET_PARTNERS_REQUEST : 'GET_PARTNERS_REQUEST',
  GET_PARTNERS_SUCCESS : 'GET_PARTNERS_SUCCESS',
  GET_PARTNERS_FAILURE : 'GET_PARTNERS_FAILURE',

  DELETE_PARTNER_REQUEST : 'DELETE_PARTNER_REQUEST',
  DELETE_PARTNER_SUCCESS : 'DELETE_PARTNER_SUCCESS',
  DELETE_PARTNER_FAILURE : 'DELETE_PARTNER_FAILURE',

  EDIT_PARTNER_REQUEST : 'EDIT_PARTNER_REQUEST',
  EDIT_PARTNER_SUCCESS : 'EDIT_PARTNER_SUCCESS',
  EDIT_PARTNER_FAILURE : 'EDIT_PARTNER_FAILURE',

  GET_SEO_PAGES : 'GET_SEO_PAGES',
  EDIT_SEO_PAGE : 'EDIT_SEO_PAGES',
  GET_SEO_BY_URL : 'GET_SEO_BY_URL',
  GET_ARTICLE_SEO_BY_URL : 'GET_ARTICLE_SEO_BY_URL'
};